http:
  routers:
    user:
      rule: "Host(`api.example.com`) && PathPrefix(`/user`)"
      service: user
      tls:
        certResolver: myresolver
        domains:
          - main: api.example.com
    product:
      rule: "Host(`api.example.com`) && PathPrefix(`/product`)"
      service: product
      tls:
        certResolver: myresolver
        domains:
          - main: api.example.com
    cart:
      rule: "Host(`api.example.com`) && PathPrefix(`/cart`)"
      service: cart
      tls:
        certResolver: myresolver
        domains:
          - main: api.example.com
    event:
      rule: "Host(`api.example.com`) && PathPrefix(`/event`)"
      service: event
      tls:
        certResolver: myresolver
        domains:
          - main: api.example.com
    web:
      rule: "Host(`web.example.com`) && PathPrefix(`/`)"
      service: web
      tls:
        certResolver: myresolver
        domains:
          - main: web.example.com

  services:
    user:
      loadBalancer:
        servers:
        - url: http://user
    product:
      loadBalancer:
        servers:
        - url: http://product
    cart:
      loadBalancer:
        servers:
        - url: http://cart
    event:
      loadBalancer:
        servers:
        - url: http://event
    web:
      loadBalancer:
        servers:
        - url: http://web
